# Site settings
title: Engineering and Computer Science Association
email: info@ecaconcordia.ca
description: > 
  The Engineering and Computer Science Association (ECA) represents all undergraduate students in the Faculty of Engineering and Computer science at Concordia University.
baseurl: "" 
url: "http://ecaconcordia.ca"

navbar: 
  - About Us
  - Societies
  - Services
  - Get Involved
  - Toolbox

# Site info
facebook_username: ECAConcordia
twitter_username: ecaconcordia
instagram_username: ECAConcordia
contact_address: >
  1455 de Maisonneuve Blvd West<br>
  Suite H-838<br>
  Montreal, Quebec, H3G 1M8<br>
contact_email: info@ecaconcordia.ca
contact_phone: 514-848-2424 ext. 7408

# Build settings
markdown: kramdown
permalink: pretty
keep_files: ["downloads", "ruby-endpoints"]
destination: ~/public_html/
